merged some scripts and made some minor changes

diff --git a/bashitsu-smb-basic-bf b/bashitsu-smb-basic-bf
--- a/bashitsu-smb-basic-bf
+++ b/bashitsu-smb-basic-bf
@@ -1,13 +1,15 @@
 #!/bin/bash
 
-# smb_basic_bf:  smbclient-based password cracker for domains that have account lockout policies
+# smbclient-based password cracker for domains that have account lockout policies.
 # the idea is to dump all the domain usernames (using your favorite netbios tool)
 # from any of the domain controllers in the target network.
 # then try just one authentication attempt per account with a password equals to the username
-# (i.e.: testuser/testuser) using this script.
+# (e.g.: testuser/testuser) using this script.
 
 # trying only one or two passwords attempts against each account with a long list of usernames
 # is what I like to call username bruteforcing rather than password bruteforcing.
+
+type -P smbclient &>/dev/null || { echo "smbclient required but not installed.  Aborting." >&2; exit 1; }
 
 if [[ $# -ne 2 ]]
 then
